# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='live_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stream',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
