# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20170208_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='live_at',
            field=models.DateTimeField(null=True),
        ),
    ]
